// Данные участников команды
export const members = [
  {
    id: '1',
    name: 'Никита',
    role: 'Frontend Developer',
    age: 30,
    avatar: 'https://picsum.photos/201',
    initials: 'Н',
    description:
      'Отвечает за переиспользуемые компоненты и треугольники для карточек. Создает модульные решения для команды.',
    contacts: {
      github: 'https://github.com/NekitMir',
      telegram: 'https://t.me/Nikita5974',
    },
    stack: ['React', 'JavaScript', 'SCSS', 'Vite', 'Feature-Sliced Design'],
    funFact: 'Может написать идеальный треугольник с закрытыми глазами 🔺',
    mood: '🎯',
  },
  {
    id: '2',
    name: 'Илья',
    role: 'Frontend Developer',
    age: 29,
    avatar: 'https://picsum.photos/203',
    initials: 'И',
    description:
      'Разрабатывает карточки участников на главной странице и лейблы карточек. Специализируется на UI компонентах.',
    contacts: {
      github: 'https://github.com/Desair1',
      telegram: 'https://t.me/Desa1r',
    },
    stack: ['React', 'JavaScript', 'SCSS', 'Vite', 'Feature-Sliced Design'],
    funFact: 'Коллекционирует редкие CSS-свойства как покемонов 🎴',
    mood: '🎨',
  },
  {
    id: '3',
    name: 'Александр',
    role: 'Frontend Developer',
    age: 25,
    avatar: 'https://picsum.photos/205',
    initials: 'А',
    description: 'Отвечает за цветовую тему приложения и страницу участников. Работает с дизайн-системой.',
    contacts: {
      github: 'https://github.com/alexander2555',
      telegram: null,
    },
    stack: ['React', 'JavaScript', 'SCSS', 'Vite', 'Feature-Sliced Design'],
    funFact: 'Видит цвета в hex-кодах и может определить #FF6B6B с расстояния 50 метров 🌈',
    mood: '🎭',
  },
  {
    id: '4',
    name: 'Иван',
    role: 'Frontend Developer',
    age: 30,
    avatar: 'https://picsum.photos/250',
    badges: ['Team Lead'],
    initials: 'И',
    description: 'Создает основные страницы: главную, избранное и настраивает роутеры. Архитектор проекта.',
    contacts: {
      github: 'https://github.com/Karez79',
      telegram: 'https://t.me/Kartez78',
    },
    stack: ['React', 'JavaScript', 'SCSS', 'Vite', 'Feature-Sliced Design'],
    funFact: 'Может объяснить любую архитектуру через аналогию с бургерами 🍔',
    mood: '👑',
  },
  {
    id: '5',
    name: 'Егор',
    role: 'Frontend Developer',
    age: 21,
    avatar: 'https://picsum.photos/209',
    initials: 'Е',
    description:
      'Разрабатывает слайдер, работает с Local Storage и создает переключатель между слайдером и сеткой карточек.',
    contacts: {
      github: 'https://github.com/Madakalov-front',
      telegram: 'https://t.me/Madakalov',
    },
    stack: ['React', 'JavaScript', 'SCSS', 'Vite', 'Feature-Sliced Design'],
    funFact: 'LocalStorage для него что дом - знает где лежит каждый ключик 🗝️',
    mood: '⚡',
  },
  {
    id: '6',
    name: 'Дамир',
    age: 50,
    avatar: 'https://picsum.photos/206',
    role: 'Frontend Developer',
    initials: 'Д',
    description: 'Создает страницу 404 и реализует Error Boundary для обработки ошибок в приложении.',
    contacts: {
      github: 'https://github.com/damaxGmail',
      telegram: 'https://t.me/Damir_i4',
    },
    stack: ['React', 'JavaScript', 'SCSS', 'Vite', 'Feature-Sliced Design'],
    funFact: 'Профессиональный ловец багов - ошибки боятся его как огня 🐛',
    mood: '🛡️',
  },
];
